public enum AbilityType {
    FROSTBITE,
    LIGHTNING_CHARGE,
    THORN_ARMOR,
    FLAME_FURY,
    FIRE_REBIRTH,
    OCEANS_GRASP,
    BURNING_CLAWS,
    RADIANT_BALANCE,
    MOLTEN_CORE,
    RAINBOW_PULSE,
    LAVA_SURGE,
    ASHEN_WINGS,
    GLACIAL_SHIELD
}
